#!/usr/bin/env bash

# migrate for Perl
if ! hash cpanm 2>/dev/null; then
    curl -L https://cpanmin.us | perl - --sudo App::cpanminus
fi

sudo cpanm Proclet::Declare

# migrate for python
sudo pip install -r requirements.txt

# migrate for ssl
if [ ! -d "./ssl" ]; then
    mkdir -p ./ssl
    cd ./ssl
    openssl genrsa -out laputa.key 2048
    openssl req -new -key laputa.key -sha256 -out laputa.csr
    openssl x509 -in laputa.csr -days 36500 -req -signkey laputa.key -sha256 -out laputa.crt
    cd ..
fi

# for laputa
if ! hash go 2>/dev/null; then
    echo "install golang..."
    os=`uname | tr [A-Z] [a-z]`
    arch=`uname -m`
    curl -O "https://storage.googleapis.com/golang/go1.7.4.${os}-${arch}.tar.gz"
    tar xzvf "go1.7.4.${os}-${arch}.tar.gz"
    sudo mv go /usr/local
    rm "go1.7.4.${os}-${arch}.tar.gz"
    mkdir -p ~/go
    echo 'export GOROOT=/usr/local/go' >> ~/.bash_profile
    echo 'export PATH=$PATH:$GOROOT/bin' >> ~/.bash_profile
    echo 'export GOPATH=~/go' >> ~/.bash_profile
    source ~/.bash_profile
fi

go get github.com/syndtr/goleveldb/leveldb
go get github.com/uber-go/zap
go get github.com/k0kubun/pp
go get github.com/kelseyhightower/envconfig
go get github.com/labstack/echo

go build -o laputa