#!/usr/bin/env perl
use strict;
use warnings;

use Cwd;
use Proclet::Declare;

my $curdir = getcwd();
my $logdir = "$curdir/log";

mkdir $logdir unless -d $logdir;

color;
env(
    LAPUTA_AKATSUKI => 'https://10.0.1.158:3000/api/ldap/felica/',
    LAPUTA_FLOOR    => 'F321',
    LOG_DIR         => $logdir,
    LM_COLOR        => 0
);

service('Castle in the sky', 'make run-staging');
service('Levistone', './levistone/levistone.py');

run;
