#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use Proclet::Declare;

my $curdir = $FindBin::Bin;

mkdir "./log" unless -d "./log";

color;
env(
    LAPUTA_CERTFILE => './ssl/laputa.crt',
    LAPUTA_KEYFILE  => './ssl/laputa.key',
    LAPUTA_AKATSUKI => 'https://10.0.1.158:3000/api/ldap/felica/',
    LAPUTA_MODE     => 'development',
    LAPUTA_FLOOR    => 'F321',
    LAPUTA_PORT     => 443,
    LOG_DIR         => "$curdir/log",
    LM_COLOR        => 1
);

service('Castle in the sky', './laputa');
service('levistone', './levistone/levistone.py');

run;
