---
- name: check installed pyenv 
  shell: which pyenv
  register: result
  ignore_errors: yes

- name: git clone pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: /home/pi/.pyenv
  when: result.rc != 0

- name: install python 2.7.13
  shell: pyenv install 2.7.13
  when: result.rc != 0

- name: pyenv version change 2.7.13
  shell: pyenv global 2.7.13
