---
- name: project migration
  become: no
  remote_user: pi
  hosts: 10.0.4.108
  roles:
    - laputa
  environment:
    PATH: /usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/home/pi/.pyenv/bin:/home/pi/.pyenv/shims:/home/pi/.plenv/bin:/home/pi/.plenv/shims
    GOPATH: /home/pi/go

