---
- name: Provision instances
  become: no
  remote_user: pi
  hosts: 10.0.4.108

  environment:
      PATH: /home/pi/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin:/usr/local/go/bin:/home/pi/go/bin:/usr/local/go/bin:/home/pi/.pyenv/bin/
      GOPATH: /home/pi/go


  tasks:
  - name: Copy .bash_profile
    copy:
        src=./.bash_profile dest=/home/pi/.bash_profile

  - name: git clone pyenv
    git:
      repo: https://github.com/yyuu/pyenv.git
      dest: /home/pi/.pyenv

  - name: install python 2.7.13
    shell:
         pyenv install 2.7.13

  - name: pyenv version change 2.7.13
    shell:
         pyenv global 2.7.13
          

