---
- name: Provision instances
  become: no
  remote_user: pi
  hosts:  10.0.4.108

  environment:
    PATH: /home/pi/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin:/usr/local/go/bin:/home/pi/go/bin:/usr/local/go/bin
    GOPATH: /home/pi/go

  tasks: 
  - name: Get go source file 
    vars:
      goversion: 1.7.4
      goarch: armv6l
      gosha256: 075c5f4446234e26c1380003ff2b050f0c7e63591410bab65355a945601bf245
    get_url: 
      url: https://storage.googleapis.com/golang/go{{ goversion }}.linux-{{ goarch }}.tar.gz 
      dest: /home/pi/go{{ goversion }}.linux-{{ goarch }}.tar.gz
      checksum: sha256:{{ gosha256 }}
  
  - name: Install go
    sudo: yes
    shell: tar -C /usr/local -xzf go1.7.4.linux-armv6l.tar.gz

  - name: Get glide
    vars:
      glideversion: v0.12.3
      glidearch: armv7
      glidesha256: cce4242c11d084f99087caaa0a42c8476a81db0cbcc83932f5821e1f29b7edb2
    get_url: 
      url: https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-{{ glideversion }}-linux-{{ glidearch }}.tar.gz 
      dest: /home/pi/linux-{{ glidearch }}.tar.gz
      checksum: sha256:{{ glidesha256 }}

  - name: Install glide
    shell:
        tar -xzf glide-v0.12.3-linux-armv7.tar.gz
    args:
        creates: linux-armv7.tar.gz

  - name: Move gilde  
    shell:
        mv ./linux-armv7/glide /usr/local/go/bin
    args:
        creates: linux-armv7

