---
- name: Provision instances
  become: no
  remote_user: pi
  hosts: 10.0.4.108

  tasks:
  - name: Copy bash_profile
    copy:
        src=/Users/e145735/ansible/bash_profile.txt dest=/home/pi/.bash_profile

  - name: git clone pyenv
    git:
      repo: https://github.com/yyuu/pyenv.git
      dest: /home/pi/.pyenv

  - name: install python 2.7.13
    shell:
         /home/pi/.pyenv/bin/pyenv install 2.7.13

  - name: pyenv version change 2.7.13
    shell:
         /home/pi/.pyenv/bin/pyenv global 2.7.13
          

