---
- name: setup perl
  become: no
  remote_user: pi
  hosts: 10.0.4.108

  environment:
      PATH: /home/pi/:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/home/pi/.plenv/bin:/home/pi/.plenv/shims
      GOPATH: /home/pi/go

  tasks: 
  - name: git clone plenv & perl-build
    git: 
      repo: '{{ item.repo }}'
      dest: '{{ item.dest }}'
    with_items:
      - repo: https://github.com/tokuhirom/plenv.git
        dest: /home/pi/.plenv
      - repo: https://github.com/tokuhirom/Perl-Build.git
        dest: /home/pi/.plenv/plugins/perl-build/

  - name: config .bash_profile
    copy: src=./.bash_profile dest=/home/pi/.bash_profile

  - name: exec shell
    shell:
        exec $SHELL -l

  - name: install perl
    shell: |
      plenv install 5.24.0 
      plenv rehash

  - name: install carton
    shell: 
        plenv install-cpanm
    shell:
        cpanm Carton
